### ISSUE TITLE
Can't find users to add to private group

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/hc-user-support#1]
Kristen Mapes is having an issue adding people to a group, and I get the same results. The group is: https://hcommons.org/groups/global-digital-humanities-symposium-planning-committee/admin/manage-members/ a good example person is  https://hcommons.org/members/gimena2/. No matter who you search for it tells you "no results found."

**Comment by mikethicke** [comment]
One issue is that no matter what search results I get, a box pops up saying 'No Results Found'.

However, the search box in Manage | Members does successfully search for members who are already in the group. It's not clear that it is supposed to find members who are not in the group. The search box under Send Invites does find members not in the group.

**Comment by bjr70** [comment]
This appears to be a non-issue. Users should be invited through "Send Invites."
